version: '3.8'

services:
  portfolio-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      # Mapeia o código fonte para hot-reload
      - .:/app
      # Preserva node_modules do container
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
